package io.github.hvna9.consultantutils.constants;

public interface Placeholder {
	public final String LOREM_IPSUM_10 = "Lorem nam.";
	public final String LOREM_IPSUM_100 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor nulla et lobortis fermentum leo.";
	public final String LOREM_IPSUM_200 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vulputate enim quam, in ultricies nulla efficitur ac. Curabitur rutrum porttitor tortor quis faucibus. Nam sodales quam mauris, non nullam.";
	public final String LOREM_IPSUM_500 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis molestie sem. Duis laoreet mattis justo, nec efficitur augue. Aliquam erat volutpat. Nulla pharetra facilisis velit et ultricies. Etiam maximus efficitur lacus, pellentesque pharetra dolor auctor ac. Fusce enim felis, faucibus sed tristique et, rutrum a nulla. Aenean cursus finibus arcu, mattis maximus ex feugiat sit amet. Proin tincidunt ac magna sed ultricies. Quisque consequat eleifend luctus. Nunc fringilla ex quis lacinia in.";
	public final String LOREM_IPSUM_1000 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sed purus eget lacus aliquet feugiat id vitae sapien. Cras congue malesuada massa et tempus. Cras justo augue, mollis in neque et, elementum vehicula risus. Maecenas ullamcorper enim ornare mauris luctus consequat. Cras a sagittis lorem. Maecenas accumsan venenatis augue sit amet venenatis. Praesent vitae quam in metus ultrices luctus. Duis dignissim augue a risus eleifend porttitor. Quisque ullamcorper consequat rutrum. Vivamus mattis eros eget nunc volutpat efficitur. Aenean sit amet pretium leo. Aenean finibus faucibus mi nec tincidunt. Etiam non lacus vitae magna tempor feugiat. Nunc gravida, sem ac euismod ultricies, leo magna mollis erat, in feugiat lacus quam ut metus. Vestibulum nisi sem, ullamcorper in mi eu, imperdiet auctor tellus. Pellentesque faucibus mi id elit faucibus, eget ultricies libero facilisis. Nam diam tortor, euismod varius risus sed, dapibus tristique ipsum. Nunc mollis hendrerit viverra fusce.";
}
